# any pod in the formbuilder-services-{{ .Values.environmentName }} namespace
# should be able to access any pod in the formbuilder-platform-{{ .Values.environmentName }} namespace
# that has a label "app=fb-submitter-api-{{ .Values.environmentName }}"
# on port 3000
# NOTE: NetworkPolicy only affects pods, Services are effectively transparent
# to them - so it doesn't matter that pod x is accessing pod y port p via
# service z port p2, you have to set up the policy between
# pod x and pod y port p
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-services-to-access-submitter
  namespace: formbuilder-platform-{{ .Values.environmentName }}
spec:
  podSelector:
    matchLabels:
      app: fb-submitter-api-{{ .Values.environmentName }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: formbuilder-services-{{ .Values.environmentName }}
    ports:
    - protocol: TCP
      port: 3000

---
# We must also allow the submitter to access any pods in the services NS
# so that it can retrieve the mail body parts & PDFs
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-submitter-to-access-services
  namespace: formbuilder-services-{{ .Values.environmentName }}
spec:
  # empty podSelector means 'all pods'
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: formbuilder-platform-{{ .Values.environmentName }}
      # This is a kubernetes 1.11 feature, the live cluster is still on 1.10
      # podSelector:
      #   matchLabels:
      #     app: fb-submitter-workers-{{ .Values.environmentName }}
    ports:
    - protocol: TCP
      port: 3000
