apiVersion: v1
kind: Secret
metadata:
  name: fb-submitter-app-secrets-{{ .Values.environmentName }}
  namespace: formbuilder-platform-{{ .Values.environmentName }}
type: Opaque
data:
  # These credentials will be used by the submitter workers
  # to SendRawEmail via Amazon SES.
  # Therefore these must have permission to perform that operation
  # defined in their user policy.
  # TODO: script this via terraform & K8s secret
  # {{ .Values.environmentName }} values:
  aws_access_key: {{ .Values.aws_access_key }}
  aws_secret_key: {{ .Values.aws_secret_key }}
  secret_key_base: {{ .Values.secret_key_base }}
  notify_api_key: {{ .Values.notify_api_key }}
  notify_save_return_email_template_id: {{ .Values.notify_save_return_email_template_id }}
  notify_save_return_email_magic_link_template_id: {{ .Values.notify_save_return_email_magic_link_template_id }}
  notify_save_return_email_progress_saved_template_id: {{ .Values.notify_save_return_email_progress_saved_template_id }}
